access-token:
  private: access-refresh-token-keys/access-token-private.key
  public: access-refresh-token-keys/access-token-public.key
refresh-token:
  private: access-refresh-token-keys/refresh-token-private.key
  public: access-refresh-token-keys/refresh-token-public.key
spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://TravelPlanner:ExvHrJA9MAnf55Ik@travelplanner.8vys92s.mongodb.net/
      database: TravelPlanner
logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8081


