
spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://TravelPlanner:ExvHrJA9MAnf55Ik@travelplanner.8vys92s.mongodb.net/
      database: TravelPlanner
logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8081


