access-token:
  private: access-refresh-token-keys/access-token-private.key
  public: access-refresh-token-keys/access-token-public.key
refresh-token:
  private: access-refresh-token-keys/refresh-token-private.key
  public: access-refresh-token-keys/refresh-token-public.key
spring:
  profiles:
    active: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: travel_planner
logging:
  level:
    org.springframework.security: DEBUG
